### ISSUE TITLE
Does it support Server Side Routing

### ISSUE THREAD

**Issue by ikwattro** [py2neo-org/py2neo#938]
Hi @technige , I hope you're having a great time at Elastic m8 .

Wondering if you would be aware of any issues py2neo could have with Neo4j's SSR ?

Cheers !

**Comment by technige** [comment]
Hey @ikwattro - I never actually used SSR, so the real answer here is that it might work, and might not. I assume that since you've opened an issue though, it probably isn't.

I never considered the design of Neo's SSR to be particularly well thought out, which is largely why I've avoided it. While I was certainly never against the idea in theory, the architecture that emerged consisted of too many random independent ideas, which generally weren't considered from an holistic perspective. And so this made system configuration harder than it needed to be, and I therefore never spent time trying to work out the exact combination of settings to made everything work together.

So ultimately, there's a very high probability that py2neo won't work with SSR in its current form, although I've never tested that.

**Comment by ikwattro** [comment]
@technige Indeed, it seems it's not using the right node when using SSR, that's ok, I just wanted to get an idea if it were supposed to be so after looking inside the codebase and tests where I couldn't find relevant ssr stuff.
