### ISSUE TITLE
Is this Project Dead?

### ISSUE THREAD

**Issue by benjamin-small** [py2neo-org/py2neo#958]
I'm looking through I'm not seeing responses from the developers or code commits. Is anybody still working on this?

**Comment by DEAN-Cherry** [comment]
Try this 
https://neo4j.com/docs/getting-started/current/languages-guides/neo4j-python/

**Comment by phreakocious** [comment]
Bumping the question before I get too attached to OGM and have to dump it.  It would be nice to not be doing tons of low level cypher stuff to load nodes and edges.

**Comment by jkminder** [comment]
Sadly yes, the main dev Nigel Small answered this [on twitter](https://twitter.com/technige/status/1648772863439036423): <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Thanks Julian. No, I&#39;ve not been at Neo4j for over a year and a half now, and I&#39;m no longer involved with the community. When I left, I tried to find someone else to take it on but was unsuccessful. I would suggest you consider it EOL, and look to the official driver instead.</p>&mdash; Nigel Small (@technige) <a href="https://twitter.com/technige/status/1648772863439036423?ref_src=twsrc%5Etfw">April 19, 2023</a></blockquote>
 Maybe the community can take it over.

**Comment by technige** [comment]
Yes, please now consider py2neo to be EOL. I do not plan to make any more updates and am currently considering whether or not to renew the domain names next month.

During my decade-long involvement with Neo4j, there was never any interest from the company in providing official staffing for the project. On leaving back in 2021, I was also unable to find a maintainer.

Given that so much time has now passed, the code will be very out of date. At least one major release, plus a bunch of other features have been shipped since I last worked on this. Therefore, another maintainer would likely have a very difficult job catching up.

I would strongly suggest looking to the official drivers as a replacement. Although I know that the functionality provided there is slimmer, the team of engineers I left behind are fantastic.

Thank you to everyone for making this such a fun part of my life. It's now time to move on.

Nigel :heart:

**Comment by phreakocious** [comment]
Anyone looking for an alternative should take a look at [neomodel](https://github.com/neo4j-contrib/neomodel) .. It offers a similar OGM solution and syntax and is back under active development.

**Comment by Thiago-Reis-Porto** [comment]
It's available again in https://pypi.org/project/py2neo/, and for older specific version on https://pypi.org/project/py2neo-history/.
